# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False)),
                ('categoria', models.TextField()),
            ],
            options={
                'ordering': ('categoria',),
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('idEmpresa', models.IntegerField(primary_key=True, serialize=False)),
                ('empresa', models.TextField()),
            ],
            options={
                'ordering': ('empresa',),
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('idGenero', models.IntegerField(primary_key=True, serialize=False)),
                ('genero', models.TextField()),
            ],
            options={
                'ordering': ('genero',),
            },
        ),
        migrations.CreateModel(
            name='HistoricoJuego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('precioVenta', models.FloatField()),
                ('precioCompra', models.FloatField()),
                ('precioIntercambio', models.FloatField()),
            ],
            options={
                'ordering': ('fecha',),
            },
        ),
        migrations.CreateModel(
            name='ImagenJuego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlImagen', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('sku', models.BigIntegerField(primary_key=True, serialize=False)),
                ('idIGDB', models.BigIntegerField(null=True)),
                ('nombre', models.TextField()),
                ('portada', models.URLField()),
                ('precioVenta', models.FloatField()),
                ('precioCompra', models.FloatField()),
                ('precioIntercambio', models.FloatField()),
                ('fechaSalida', models.DateField(null=True)),
                ('actualizado', models.DateField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lowpricex_app.Categoria')),
                ('desarrolladores', models.ManyToManyField(related_name='desarrolladores', to='lowpricex_app.Empresa')),
                ('generos', models.ManyToManyField(to='lowpricex_app.Genero')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('idKeyword', models.IntegerField(primary_key=True, serialize=False)),
                ('keyword', models.TextField()),
            ],
            options={
                'ordering': ('keyword',),
            },
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('idPlataforma', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('abreviatura', models.TextField()),
                ('logo', models.URLField()),
            ],
            options={
                'ordering': ('abreviatura',),
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('idTema', models.IntegerField(primary_key=True, serialize=False)),
                ('tema', models.TextField()),
            ],
            options={
                'ordering': ('tema',),
            },
        ),
        migrations.CreateModel(
            name='VideoJuego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlVideo', models.URLField()),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lowpricex_app.Juego')),
            ],
        ),
        migrations.AddField(
            model_name='juego',
            name='keywords',
            field=models.ManyToManyField(to='lowpricex_app.Keyword'),
        ),
        migrations.AddField(
            model_name='juego',
            name='plataforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lowpricex_app.Plataforma'),
        ),
        migrations.AddField(
            model_name='juego',
            name='publishers',
            field=models.ManyToManyField(related_name='publishers', to='lowpricex_app.Empresa'),
        ),
        migrations.AddField(
            model_name='juego',
            name='temas',
            field=models.ManyToManyField(to='lowpricex_app.Tema'),
        ),
        migrations.AddField(
            model_name='imagenjuego',
            name='juego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lowpricex_app.Juego'),
        ),
        migrations.AddField(
            model_name='historicojuego',
            name='juego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lowpricex_app.Juego'),
        ),
    ]
