# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lowpricex_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuegoDetalles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.TextField()),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lowpricex_app.Juego')),
            ],
        ),
    ]
